version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region eu-north-1 --no-include-email)
      - REPOSITORY_URI=347859197403.dkr.ecr.eu-north-1.amazonaws.com/arnthorhs/sensorwebsite
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=v.0.0.2
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 347859197403.dkr.ecr.eu-north-1.amazonaws.com/arnthorhs/sensorwebsite:$IMAGE_TAG
      - docker push 347859197403.dkr.ecr.eu-north-1.amazonaws.com/arnthorhs/sensorwebsite:latest
artifacts:
    files: imagedefinitions.json