"""measurements table

Revision ID: 1611ede3a703
Revises: 
Create Date: 2020-02-21 15:02:06.720140

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1611ede3a703'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measurement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor', sa.String(length=64), nullable=True),
    sa.Column('val', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_measurement_sensor'), 'measurement', ['sensor'], unique=False)
    op.create_index(op.f('ix_measurement_timestamp'), 'measurement', ['timestamp'], unique=False)
    op.create_index(op.f('ix_measurement_val'), 'measurement', ['val'], unique=False)
    op.drop_table('measurements')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measurements',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sensor', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('val', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='measurements_pkey')
    )
    op.drop_index(op.f('ix_measurement_val'), table_name='measurement')
    op.drop_index(op.f('ix_measurement_timestamp'), table_name='measurement')
    op.drop_index(op.f('ix_measurement_sensor'), table_name='measurement')
    op.drop_table('measurement')
    # ### end Alembic commands ###
