"""temp/humidity table

Revision ID: 4d23ea5aa265
Revises: 1611ede3a703
Create Date: 2020-02-21 15:48:02.069465

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4d23ea5aa265'
down_revision = '1611ede3a703'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('humidity',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('hour', sa.Integer(), nullable=True),
    sa.Column('minute', sa.Integer(), nullable=True),
    sa.Column('second', sa.Integer(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('timestamp')
    )
    op.create_index(op.f('ix_humidity_day'), 'humidity', ['day'], unique=False)
    op.create_index(op.f('ix_humidity_hour'), 'humidity', ['hour'], unique=False)
    op.create_index(op.f('ix_humidity_minute'), 'humidity', ['minute'], unique=False)
    op.create_index(op.f('ix_humidity_month'), 'humidity', ['month'], unique=False)
    op.create_index(op.f('ix_humidity_second'), 'humidity', ['second'], unique=False)
    op.create_index(op.f('ix_humidity_value'), 'humidity', ['value'], unique=False)
    op.create_index(op.f('ix_humidity_year'), 'humidity', ['year'], unique=False)
    op.create_table('temperature',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('hour', sa.Integer(), nullable=True),
    sa.Column('minute', sa.Integer(), nullable=True),
    sa.Column('second', sa.Integer(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('timestamp')
    )
    op.create_index(op.f('ix_temperature_day'), 'temperature', ['day'], unique=False)
    op.create_index(op.f('ix_temperature_hour'), 'temperature', ['hour'], unique=False)
    op.create_index(op.f('ix_temperature_minute'), 'temperature', ['minute'], unique=False)
    op.create_index(op.f('ix_temperature_month'), 'temperature', ['month'], unique=False)
    op.create_index(op.f('ix_temperature_second'), 'temperature', ['second'], unique=False)
    op.create_index(op.f('ix_temperature_value'), 'temperature', ['value'], unique=False)
    op.create_index(op.f('ix_temperature_year'), 'temperature', ['year'], unique=False)
    op.drop_index('ix_measurement_sensor', table_name='measurement')
    op.drop_index('ix_measurement_timestamp', table_name='measurement')
    op.drop_index('ix_measurement_val', table_name='measurement')
    op.drop_table('measurement')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measurement',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sensor', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('val', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='measurement_pkey')
    )
    op.create_index('ix_measurement_val', 'measurement', ['val'], unique=False)
    op.create_index('ix_measurement_timestamp', 'measurement', ['timestamp'], unique=False)
    op.create_index('ix_measurement_sensor', 'measurement', ['sensor'], unique=False)
    op.drop_index(op.f('ix_temperature_year'), table_name='temperature')
    op.drop_index(op.f('ix_temperature_value'), table_name='temperature')
    op.drop_index(op.f('ix_temperature_second'), table_name='temperature')
    op.drop_index(op.f('ix_temperature_month'), table_name='temperature')
    op.drop_index(op.f('ix_temperature_minute'), table_name='temperature')
    op.drop_index(op.f('ix_temperature_hour'), table_name='temperature')
    op.drop_index(op.f('ix_temperature_day'), table_name='temperature')
    op.drop_table('temperature')
    op.drop_index(op.f('ix_humidity_year'), table_name='humidity')
    op.drop_index(op.f('ix_humidity_value'), table_name='humidity')
    op.drop_index(op.f('ix_humidity_second'), table_name='humidity')
    op.drop_index(op.f('ix_humidity_month'), table_name='humidity')
    op.drop_index(op.f('ix_humidity_minute'), table_name='humidity')
    op.drop_index(op.f('ix_humidity_hour'), table_name='humidity')
    op.drop_index(op.f('ix_humidity_day'), table_name='humidity')
    op.drop_table('humidity')
    # ### end Alembic commands ###
