"""temp/humidity 3 table

Revision ID: 76e14e58df74
Revises: 4d23ea5aa265
Create Date: 2020-02-21 16:39:43.906912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76e14e58df74'
down_revision = '4d23ea5aa265'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_humidity_day', table_name='humidity')
    op.drop_index('ix_humidity_hour', table_name='humidity')
    op.drop_index('ix_humidity_minute', table_name='humidity')
    op.drop_index('ix_humidity_month', table_name='humidity')
    op.drop_index('ix_humidity_second', table_name='humidity')
    op.drop_index('ix_humidity_year', table_name='humidity')
    op.drop_column('humidity', 'second')
    op.drop_column('humidity', 'month')
    op.drop_column('humidity', 'minute')
    op.drop_column('humidity', 'day')
    op.drop_column('humidity', 'year')
    op.drop_column('humidity', 'hour')
    op.drop_index('ix_temperature_day', table_name='temperature')
    op.drop_index('ix_temperature_hour', table_name='temperature')
    op.drop_index('ix_temperature_minute', table_name='temperature')
    op.drop_index('ix_temperature_month', table_name='temperature')
    op.drop_index('ix_temperature_second', table_name='temperature')
    op.drop_index('ix_temperature_year', table_name='temperature')
    op.drop_column('temperature', 'second')
    op.drop_column('temperature', 'month')
    op.drop_column('temperature', 'minute')
    op.drop_column('temperature', 'day')
    op.drop_column('temperature', 'year')
    op.drop_column('temperature', 'hour')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temperature', sa.Column('hour', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('temperature', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('temperature', sa.Column('day', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('temperature', sa.Column('minute', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('temperature', sa.Column('month', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('temperature', sa.Column('second', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index('ix_temperature_year', 'temperature', ['year'], unique=False)
    op.create_index('ix_temperature_second', 'temperature', ['second'], unique=False)
    op.create_index('ix_temperature_month', 'temperature', ['month'], unique=False)
    op.create_index('ix_temperature_minute', 'temperature', ['minute'], unique=False)
    op.create_index('ix_temperature_hour', 'temperature', ['hour'], unique=False)
    op.create_index('ix_temperature_day', 'temperature', ['day'], unique=False)
    op.add_column('humidity', sa.Column('hour', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('humidity', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('humidity', sa.Column('day', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('humidity', sa.Column('minute', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('humidity', sa.Column('month', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('humidity', sa.Column('second', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index('ix_humidity_year', 'humidity', ['year'], unique=False)
    op.create_index('ix_humidity_second', 'humidity', ['second'], unique=False)
    op.create_index('ix_humidity_month', 'humidity', ['month'], unique=False)
    op.create_index('ix_humidity_minute', 'humidity', ['minute'], unique=False)
    op.create_index('ix_humidity_hour', 'humidity', ['hour'], unique=False)
    op.create_index('ix_humidity_day', 'humidity', ['day'], unique=False)
    # ### end Alembic commands ###
