"""measurements table

Revision ID: ac4d9caa64b5
Revises: 
Create Date: 2020-04-03 11:38:52.101587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac4d9caa64b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_measurements_day'), 'measurements', ['day'], unique=False)
    op.create_index(op.f('ix_measurements_hour'), 'measurements', ['hour'], unique=False)
    op.create_index(op.f('ix_measurements_hum'), 'measurements', ['hum'], unique=False)
    op.create_index(op.f('ix_measurements_ill'), 'measurements', ['ill'], unique=False)
    op.create_index(op.f('ix_measurements_minute'), 'measurements', ['minute'], unique=False)
    op.create_index(op.f('ix_measurements_month'), 'measurements', ['month'], unique=False)
    op.create_index(op.f('ix_measurements_pres'), 'measurements', ['pres'], unique=False)
    op.create_index(op.f('ix_measurements_second'), 'measurements', ['second'], unique=False)
    op.create_index(op.f('ix_measurements_temp'), 'measurements', ['temp'], unique=False)
    op.create_index(op.f('ix_measurements_uv'), 'measurements', ['uv'], unique=False)
    op.create_index(op.f('ix_measurements_year'), 'measurements', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_measurements_year'), table_name='measurements')
    op.drop_index(op.f('ix_measurements_uv'), table_name='measurements')
    op.drop_index(op.f('ix_measurements_temp'), table_name='measurements')
    op.drop_index(op.f('ix_measurements_second'), table_name='measurements')
    op.drop_index(op.f('ix_measurements_pres'), table_name='measurements')
    op.drop_index(op.f('ix_measurements_month'), table_name='measurements')
    op.drop_index(op.f('ix_measurements_minute'), table_name='measurements')
    op.drop_index(op.f('ix_measurements_ill'), table_name='measurements')
    op.drop_index(op.f('ix_measurements_hum'), table_name='measurements')
    op.drop_index(op.f('ix_measurements_hour'), table_name='measurements')
    op.drop_index(op.f('ix_measurements_day'), table_name='measurements')
    # ### end Alembic commands ###
